language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - srecord
      - gcovr

before_install:
  - pip install --user cpp-coveralls

install:
  - ./autogen.sh
  - ./configure --enable-gcov

script: 
  - make
  - make firmware_tool
  - make server
  - make assets
  - ./utils/server/server -f assets/fake_firmware_dead >/dev/null 2>&1 &
  - make check

after_success:
    - coveralls --exclude ext --exclude test
